[hud]
visible = 1

[clock]
enabled = 1
position = top_right
size = medium
ontop = 0

[system]
enabled = 1
position = top_right
size = medium
ontop = 0

[network]
enabled = 1
position = top_left
size = medium
ontop = 0

[battery]
enabled = 1
position = top_left
size = medium
ontop = 0
