Section "InputClass"
    Identifier "NEXUS touchpad"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "Tapping" "on"
    Option "TappingDrag" "on"
    Option "NaturalScrolling" "false"
    Option "DisableWhileTyping" "on"
EndSection
