Section "InputClass"
    Identifier "NEXUS touchscreen long-press right click"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Driver "evdev"
    Option "EmulateThirdButton" "1"
    Option "EmulateThirdButtonTimeout" "600"
    Option "EmulateThirdButtonButton" "3"
    Option "EmulateThirdButtonMoveThreshold" "30"
EndSection
